### ISSUE TITLE
s25rttr fails to compile with boost-1.71.0 

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1117]
there are actually three errors in a row: 

```In file included from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:42:
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/common/include/helpers/containerUtils.h: In instantiation of ‘auto helpers::findPred(T&, T_Predicate&&) [with T = boost::ptr_vector<AIPlayer>; T_Predicate = GameClient::ToggleHumanAIPlayer()::<lambda(const auto:1&)>]’:
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1752:136:   required from here
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/common/include/helpers/containerUtils.h:99:30: error: ‘begin’ was not declared in this scope
     return std::find_if(begin(container), end(container), std::forward<T_Predicate>(predicate));
                         ~~~~~^~~~~~~~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/common/include/helpers/containerUtils.h:99:30: note: suggested alternatives:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/string:51,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/stdexcept:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/array:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/tuple:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/functional:54,
                 from /usr/include/boost/config/no_tr1/functional.hpp:21,
                 from /usr/include/boost/smart_ptr/intrusive_ptr.hpp:24,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/GameCommand.h:21,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.h:22,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:19:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/range_access.h:105:37: note:   ‘std::begin’
   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
                                     ^~~~~
In file included from /usr/include/boost/dll/config.hpp:60,
                 from /usr/include/boost/dll/shared_library.hpp:15,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/drivers/DriverWrapper.h:20,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/drivers/VideoDriverWrapper.h:20,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:39:
/usr/include/boost/filesystem/operations.hpp:1364:5: note:   ‘boost::filesystem::begin’
     begin(const recursive_directory_iterator& iter) BOOST_NOEXCEPT
     ^~~~~
In file included from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/ptr_container/detail/reversible_ptr_container.hpp:30,
                 from /usr/include/boost/ptr_container/ptr_sequence_adapter.hpp:20,
                 from /usr/include/boost/ptr_container/ptr_deque.hpp:20,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/MessageQueue.h:21,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/NetworkPlayer.h:21,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.h:24,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:19:
/usr/include/boost/range/begin.hpp:114:61: note:   ‘boost::range_adl_barrier::begin’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type begin( const T& r )
                                                             ^~~~~
In file included from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:42:
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/common/include/helpers/containerUtils.h:99:46: error: ‘end’ was not declared in this scope
     return std::find_if(begin(container), end(container), std::forward<T_Predicate>(predicate));
                                           ~~~^~~~~~~~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/common/include/helpers/containerUtils.h:99:46: note: suggested alternatives:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/string:51,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/stdexcept:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/array:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/tuple:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/functional:54,
                 from /usr/include/boost/config/no_tr1/functional.hpp:21,
                 from /usr/include/boost/smart_ptr/intrusive_ptr.hpp:24,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/GameCommand.h:21,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.h:22,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:19:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/range_access.h:107:37: note:   ‘std::end’
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
In file included from /usr/include/boost/dll/config.hpp:60,
                 from /usr/include/boost/dll/shared_library.hpp:15,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/drivers/DriverWrapper.h:20,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/drivers/VideoDriverWrapper.h:20,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:39:
/usr/include/boost/filesystem/operations.hpp:1367:32: note:   ‘boost::filesystem::end’
   recursive_directory_iterator end(const recursive_directory_iterator&) BOOST_NOEXCEPT
                                ^~~
In file included from /usr/include/boost/range/functions.hpp:19,
                 from /usr/include/boost/ptr_container/detail/reversible_ptr_container.hpp:30,
                 from /usr/include/boost/ptr_container/ptr_sequence_adapter.hpp:20,
                 from /usr/include/boost/ptr_container/ptr_deque.hpp:20,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/MessageQueue.h:21,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/NetworkPlayer.h:21,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.h:24,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:19:
/usr/include/boost/range/end.hpp:108:61: note:   ‘boost::range_adl_barrier::end’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type end( const T& r )
                                                             ^~~
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp: In member function ‘void GameClient::ToggleHumanAIPlayer()’:
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1752:10: error: ‘void it’ has incomplete type
     auto it = helpers::findPred(game->aiPlayers_, [id = this->GetPlayerId()](const auto& player) { return player.GetPlayerId() == id; });
          ^~

```

full log: [boost-1.71.0.log.zip](https://github.com/Return-To-The-Roots/s25client/files/3707003/boost-1.71.0.log.zip)
