### ISSUE TITLE
Issue opening game on macOS 3/4 of window is red

### ISSUE THREAD

**Issue by diwilli** [Return-To-The-Roots/s25client#1621]
under a fully updated macOS 13.5

This happens on both latest stable 0.9.5 and latest nightly s25rttr_20230814-e37a322209cffb00fda4afd50c87b8f7e8261083-darwin.x86_64.tar.bz2

Version 0.8.1 doesn't have this issue and launches correctly.

<img width="1303" alt="Screenshot 2023-08-23 at 13 43 23" src="https://github.com/Return-To-The-Roots/s25client/assets/14251725/c360dc7b-1740-492c-837e-0e469bf9e822">

Happy to test updates as they're available.

**Comment by diwilli** [comment]
I'm intending to git bisect this, and try and work out where it breaks.

The only version I can get to build is v0.9.5, trying to build anything before that gives me the following errors (I can't seem to workout where to set the -Wno-deprecated-copy flag to avoid this (I'm not a C/C++ developer):

`In file included from /Users/dan/rttr/s25client/libs/common/include/Rect.h:7:
/Users/dan/rttr/s25client/libs/common/include/Point.h:27:15: error: definition of implicit copy assignment operator for 'Point<float>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
    constexpr Point(const Point&) = default;
              ^
/Users/dan/rttr/s25client/libs/libGamedata/gameData/TerrainDesc.cpp:147:24: note: in implicit copy assignment operator for 'Point<float>' first required here
            result.tip = middleBottom;
                       ^
1 error generated.
make[2]: *** [libs/libGamedata/CMakeFiles/gamedata.dir/gameData/TerrainDesc.cpp.o] Error 1
make[1]: *** [libs/libGamedata/CMakeFiles/gamedata.dir/all] Error 2
make: *** [all] Error 2`

Any pointers?

**Comment by diwilli** [comment]
I've found -DRTTR_ENABLE_WERROR=ON, setting this to -DRTTR_ENABLE_WERROR=OFF seems to do the trick :)

**Comment by Flamefire** [comment]
> Which feels like an actual code issue, and I'm sorry I don't know how to solve that one.

When you checkout different commits (e.g. when bisecting) you need to also checkout the submodules used at that version, i.e. `git submodule update`. What you see is basically: The submodule was changed removing a function and you have a version of the main code still using the function or the other way round: Main code using a function introduced in a later version of the submodule.

**Comment by 8986ca6c** [comment]
Hi, I can run it on MacOS 13.0.1 via s25client. Whole window is used. So no problems at all.

After using s25update, the bug appears. So I think it has to do with the update procedure

**Comment by 8986ca6c** [comment]
I recommend not to start the s25client.app but the s25client in s25client.app/Contents/MacOS/ 

hold command key and right-click on the s25client.app to open it inFinder and navigate to the path.

**Comment by diwilli** [comment]
I'll try and test it tomorrow on macOS 14.1 latest.
I wasn't using s25update.  Maybe it's related to macOS / version conflict.

What version were you using?

**Comment by 8986ca6c** [comment]
I used the stable version 0.9.5

**Comment by 8986ca6c** [comment]
I updated now to MacOS 14.1 and RTTR continues working. How did you start the program? If you used the s25client.app then the update was executed automatically.

**Comment by 8986ca6c** [comment]
Other Workaround. More convenient (if you are able to run the s25client.app (the App with the S2 Logo. I was not able to use this on MacOS 13.0.1:

I assume you installed it in your Applications folder. After installing, so before the first launch of the app do the following. Go to /Applications/s25client.app/Contents/MacOS and rename s25update. I used s25update_rename as new name. The important thing is, it needs a new name such that it cannot be found. Deleting should also work, but I did not test it.

**Comment by Ekliptor** [comment]
This issue still persists with latest source from `git pull`on OSX 14.2.1.
Which commit specifically caused it to break? Would love to have a fix.

**Comment by Flamefire** [comment]
> Which commit specifically caused it to break? Would love to have a fix.

That is the big question. @diwilli did you found anything by bisecting?

@Ekliptor or who else wants to try bisecting the issue (we can't do that due to missing bare metal Mac) here a short guide:
- Be able to build and run latest sources (after `git checkout master && git pull && git submodule update --init`)
- Go back in history until you find a working commit (e.g. 0.8.1)
- Check that out and it's submodules (`git checkout 0.8.1 && git pull && git submodule update --init`)
- Build and verify it works.
- Now start bisecting (semi-automatic search reducing the amount of commits to test in half):
- `git bisect start master 0.8.1`
- Now for each step do `git submodule update --init`, build and test. Then tell git about it via `git bisect good` or `git bisect bad` which will give you the next commit to test
- until it finally tells you the bad one (sth like "215456 is the first bad commit". Post that here

**Comment by Ekliptor** [comment]
It's working correctly with the latest `v0.9.2`. So the issue started between latest tag and some recent commits in master. The only things I needed to change were some `sprintf()`calls to `snprintf()` because clang aborts with a deprecated error otherwise.

**Comment by Flamefire** [comment]
@Ekliptor You can pass `-DRTTR_ENABLE_WERROR=OFF` to cmake to avoid having to modify the source for those warnings. That should make the bisecting easier.

**Comment by Ekliptor** [comment]
I found the commit that broke the red screen:

```
git bisect good
c89d5d5618d3e20b0d8e56c75edb626f6477e968 is the first bad commit
commit c89d5d5618d3e20b0d8e56c75edb626f6477e968
Author: Florian Albrechtskirchinger <falbrechtskirchinger@gmail.com>
Date:   Sun Jul 9 11:51:56 2023 +0200

    Enable HighDPI support in SDL2
    
    Even though the SDL2 video driver is using SDL_GetWindowSize() and
    SDL_GL_GetDrawableSize() to be DPI-aware, when creating a window,
    HighDPI support was never actually requested.

 extras/videoDrivers/SDL2/VideoSDL2.cpp | 9 +++++++--
 1 file changed, 7 insertions(+), 2 deletions(-)
```

**Comment by Flamefire** [comment]
Uff, ok. This was introduced in #1594 by @falbrechtskirchinger who might be more familiar with this part.
My suspicion is that `GetRenderSize` shouldn't return a scaled render size but the true render size and we need to check [its usages](https://github.com/search?q=repo%3AReturn-To-The-Roots%2Fs25client%20GetRenderSize&type=code), or that the scaling is the wrong way round at https://github.com/Return-To-The-Roots/s25client/pull/1594/files#diff-b5b38a3930a1a7e323ee58aa4e287c55f4f8d4a69be4680f39976237295540b7R86 or possibly just the dpiscale calculation at https://github.com/Return-To-The-Roots/s25client/pull/1594/files#diff-b5b38a3930a1a7e323ee58aa4e287c55f4f8d4a69be4680f39976237295540b7R80-R81 as @falbrechtskirchinger wrote he just tested it with `windowSize == renderSize` which yields a `dpiscale` of 1

Possibly the logic using that to get a GuiScaleRange is the cause: https://github.com/Return-To-The-Roots/s25client/pull/1594/files#diff-b5b38a3930a1a7e323ee58aa4e287c55f4f8d4a69be4680f39976237295540b7R111-R121

Also suspicous to me is the use of the window sizes for the viewport at https://github.com/Return-To-The-Roots/s25client/pull/1594/files#diff-4859828a67bfa671f97fdc7ecd34979fb84152f9f681aa4369788eddc5701c3dR312-R313 Maybe this should have been the unscaled render size.

@Ekliptor Can you check&post your values of `renderSize_`, `windowSize_` and `dpiScale_` with and without the `SDL_WINDOW_ALLOW_HIGHDPI` flag?   
And can you try changing https://github.com/Return-To-The-Roots/s25client/blob/2c9c492fa7e98bb65ad4eab0d23dd4ccea18d0b9/libs/s25main/drivers/VideoDriverWrapper.cpp#L308 to `const Extent renderSize = getGuiScale().screenToView<Extent>(videodriver->GetRenderSize());`. This is just an idea which might work but I guess it is more complicated than that.

Thinking about it I have doubts about how #1594 is supposed to work, especially for `windowSize != renderSize`. I mean we do want to render e.g. background images on the full render size as otherwise what we see here is happening. And we want to have some things larger, but do we really? And which elements should be larger? Or do we want to zoom everything?

**Comment by Ekliptor** [comment]
Thx for the quick feedback over the holidays.

Changing `renderSize`as suggested didn't help.

The sizes with ALLOW_HIGHDPI (buggy red screen):
```

Loaded video driver "(SDL2) OpenGL via SDL2-Library"
render size x: 3584 y: 1936
window size width: 1792 height: 968
dpi scale: 2
```

And the working screen:
```
Loaded video driver "(SDL2) OpenGL via SDL2-Library"
render size x: 1792 y: 968
window size width: 1792 height: 968
dpi scale: 1
```

**Comment by audiofeature** [comment]
I have nearly the same issue on Mac OS 13.6.3 (22G436) on a Macbook Pro 14" 2021. 
Only the lower left quarter of the screen is populated with the S2 graphics / main screen. The rest of the screen is black (not red). Moreover the mouse can only move in the upper half of that quarter area. That means I can enter the Settings screen but cannot reach the graphics setting as the button Graphics cannot be reached by the mouse.

Any news / findings in this Mac issue? I
t practically renders RTTR unusable on newer Macs.

**Comment by 8986ca6c** [comment]
Hi,
Does my workaround solve the problem?

See one of the comments above…

Thomas Lidy ***@***.***> schrieb am So. 18. Feb. 2024 um
23:41:

**Comment by chellmann** [comment]
> I have nearly the same issue on Mac OS 13.6.3 (22G436) on a Macbook Pro 14" 2021. Only the lower left quarter of the screen is populated with the S2 graphics / main screen. The rest of the screen is black (not red). Moreover the mouse can only move in the upper half of that quarter area. That means I can enter the Settings screen but cannot reach the graphics setting as the button Graphics cannot be reached by the mouse.
> 
> Any news / findings in this Mac issue? I t practically renders RTTR unusable on newer Macs.

same here.

**Comment by jewesta** [comment]
> Hi, Does my workaround solve the problem?

Hi, wasn‘t asked, but just wanted to chime in that I have the exact same issue @audiofeature described and that [the workaround](https://github.com/Return-To-The-Roots/s25client/issues/1621#issuecomment-1791454568) (temporarily killing the updater) worked for me on 0.9.5.

Am on a MacBook Pro 2019 running Sonoma 14.3.1.

**Comment by tiennou** [comment]
I hit this, and wanted to try and help debugging. Sadly I can't get cmake to build:
```
cmake ..                           
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CMake 3.28.3
CMake Error at CMakeLists.txt:30 (include):
  include could not find requested file:

    EnableCCache


CMake Error at CMakeLists.txt:78 (include):
  include could not find requested file:

    EnsureOutOfSourceBuild


-- Configuring for native compiling to Darwin-22.5.0 on arm64
-- Using platform config cmake/darwin.cmake
CMake Error at cmake/darwin.cmake:6 (include):
  include could not find requested file:

    DetectOsXArchs
Call Stack (most recent call first):
  CMakeLists.txt:107 (include)


CMake Error at cmake/darwin.cmake:7 (detect_osx_archs):
  Unknown CMake command "detect_osx_archs".
Call Stack (most recent call first):
  CMakeLists.txt:107 (include)


-- Configuring incomplete, errors occurred!
```

Where can I find that module? It doesn't look like something that's from CMake's stdlib.

**Comment by tiennou** [comment]
Okay, I have a fix for the viewport:
```
diff --git c/libs/s25main/drivers/VideoDriverWrapper.cpp i/libs/s25main/drivers/VideoDriverWrapper.cpp
index 7daa4801c..15d19d2e5 100644
--- c/libs/s25main/drivers/VideoDriverWrapper.cpp
+++ i/libs/s25main/drivers/VideoDriverWrapper.cpp
@@ -305,19 +305,19 @@ void VideoDriverWrapper::RenewViewport()
     if(!videodriver->IsOpenGL() || !renderer_)
         return;
 
-    const Extent renderSize = videodriver->GetRenderSize();
+    const Extent renderSize = getGuiScale().viewToScreen<Extent>(videodriver->GetRenderSize());
     const VideoMode windowSize = videodriver->GetWindowSize();
 
     // Set the viewport and scissor area to the entire window
-    glViewport(0, 0, windowSize.width, windowSize.height);
-    glScissor(0, 0, windowSize.width, windowSize.height);
+    glViewport(0, 0, renderSize.x, renderSize.y);
+    glScissor(0, 0, renderSize.x, renderSize.y);
 
     // Orthogonale Matrix erstellen
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
 
     // 0,0 should be top left corner
-    glOrtho(0, renderSize.x, renderSize.y, 0, -100, 100);
+    glOrtho(0, windowSize.width, windowSize.height, 0, -100, 100);
 
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
```

That makes the rendering appear correctly (only testing the menu at the moment). The mouse bounding box is still out of whack though. I'm guessing it needs to have the dpi scale applied to it, as I only have access to the top-right quarter of the screen before I hit the actual screen bottom/right and get clamped there.

**Comment by thschober** [comment]
I searched a little through the code and found the root of the problem. It's the scaling of the displayed content. You can temporarily make the game running (even the nightly build from the homepage) if you set the resolution of your Mac to full

For example select 4480 x 2250 here. Then the font size is incredibly small but the game itself works.
<img width="546" alt="image" src="https://github.com/Return-To-The-Roots/s25client/assets/94794232/71b333f6-daae-4a20-a04d-b3c16d3256f8">

The problem seems to be in GuiScale.h
`
class GuiScale
{
public:
    constexpr GuiScale(unsigned percent) noexcept
        : percent_(percent), scaleViewToScreen_(percent_ / 100.f), scaleScreenToView_(1.f / scaleViewToScreen_)
    {}
`
Here the calculation is percent based and does not take scaling of the contents into account. So the scaleScreenToView multiplier is invalid.

I am currently checking how to fix this but until it is fixed just set the scaling of your Mac screen like described above and the game works (at least for me)

**Comment by cwscws** [comment]
The author of the Visual Pinball Standalone Player had the same problem. He added the option "HighDPI = 0 / 1" to the ini file. Maybe you can use his code. His repository can be found here: https://github.com/jsm174/vpinball/actions

**Comment by carpusmedia** [comment]
> I have nearly the same issue on Mac OS 13.6.3 (22G436) on a Macbook Pro 14" 2021. Only the lower left quarter of the screen is populated with the S2 graphics / main screen. The rest of the screen is black (not red). Moreover the mouse can only move in the upper half of that quarter area. That means I can enter the Settings screen but cannot reach the graphics setting as the button Graphics cannot be reached by the mouse.
> 
> Any news / findings in this Mac issue? I t practically renders RTTR unusable on newer Macs.

@audiofeature 

Did you manage to find a solution to this? I'm having the exact same problem on my Apple M1 Max, OS 14.6 (23G80)

**Comment by carpusmedia** [comment]
> > Other Workaround. More convenient (if you are able to run the s25client.app (the App with the S2 Logo. I was not able to use this on MacOS 13.0.1:
> > I assume you installed it in your Applications folder. After installing, so before the first launch of the app do the following. Go to /Applications/s25client.app/Contents/MacOS and rename s25update. I used s25update_rename as new name. The important thing is, it needs a new name such that it cannot be found. Deleting should also work, but I did not test it.
> > start the app.
> 
> Okay folks, until this will be resolved, the beforementioned workaround clearly works, thanks! **Don't forget to rename that file before the first run** :)
> 
> Macbook Pro 2020 (13-inch), macOS Sonoma Version 14.2 (23C64)

Tried this, unfortunately did not help in my case. 16-inch 2021 Apple M1 Max, OS 14.6 (23G80)

**Comment by carpusmedia** [comment]
> I searched a little through the code and found the root of the problem. It's the scaling of the displayed content. You can temporarily make the game running (even the nightly build from the homepage) if you set the resolution of your Mac to full
> 
> For example select 4480 x 2250 here. Then the font size is incredibly small but the game itself works. <img alt="image" width="546" src="https://private-user-images.githubusercontent.com/94794232/328011418-71b333f6-daae-4a20-a04d-b3c16d3256f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDYxOTcsIm5iZiI6MTcyMzMwNTg5NywicGF0aCI6Ii85NDc5NDIzMi8zMjgwMTE0MTgtNzFiMzMzZjYtZGFhZS00YTIwLWEwNGQtYjNjMTZkMzI1NmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE2MDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDAyN2Q5ZjkxYTFmOTdiY2ZhYjBmMjYxYjU2ZDgyMWE3OTkyOWE2YWZlODEyNTAxMmRkZTdmYTFkYjcwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-xHG1dq3azKDOnhFU2l0ZTUPo6LaPpf4o4ecNKC0ks0">
> 
> Additionally set the Screen size also to this value in the CONFIG.INI
> 
> ```
> [video]
> fullscreen_width=4480
> fullscreen_height=2520
> The problem seems to be in GuiScale.h
> ```
> 
> The problem is somehow the scaling factors which don't seem to take the content scaling into account.
> 
> ```
> class GuiScale
> {
> public:
>     constexpr GuiScale(unsigned percent) noexcept
>         : percent_(percent), scaleViewToScreen_(percent_ / 100.f), scaleScreenToView_(1.f / scaleViewToScreen_)
>     {}
> ```
> 
> Here the calculation is percent based and does not take scaling of the contents into account. So the scaleScreenToView multiplier is invalid.
> 
> I am currently checking how to fix this but until it is fixed just set the scaling of your Mac screen like described above and the game works (at least for me)

Tried this, while it it does make the RTTR windows the correct size the mouse still can't reach the mid-lower part of the screen.

![Screenshot 2024-08-10 at 19 19 10](https://github.com/user-attachments/assets/8841ecf9-87b7-4063-a650-09246bd0a458)

**Comment by carpusmedia** [comment]
I've solved this on my end by changing the screen resolution to 1920x1200, now the mouse tracks within the whole window. This resolution results in a screen where the text is a bit blurry, but I'll simply change it back to the default 1728x1117 after I'm done playing.

I didn't need to touch the CONFIG.INI file (located here /Users/carpusmedia/Library/Application Support/Return To The Roots) in this case, looks like this by default:

```
[global]
version=13
gameversion=67e6069a7cc3a7826fae4ca09a26c941e1be0bae
submit_debug_data=1
use_upnp=1
smartCursor=1
debugMode=0
showGFInfo=0

[video]
fullscreen_width=960
fullscreen_height=600
windowed_width=960
windowed_height=600
fullscreen=0
framerate=0
vbo=1
shared_textures=1
gui_scale=110

[language]
language=

[driver]
video=(SDL2) OpenGL via SDL2-Library
audio=(SDL2) Audio via SDL2_mixer-Library
...
```

**So if all else fails try starting the game using different sets of screen resolution until you find something that works for you.**

![Screenshot 2024-08-10 at 20 15 59](https://github.com/user-attachments/assets/42779371-82c2-49cd-af47-23a6a7768d8f)

**Comment by carpusmedia** [comment]
Last update for me, I got it working without having to change the macOS screen resolution each time I want to play the game: 

1. Adjust Mac Screen Resolution: Test different screen resolutions until the entire game is visible and the mouse tracks correctly within the window.

2. Set Fullscreen Mode in Game:
Start the game and navigate to Options > Graphics. Set the mode to "Fullscreen."
Alternatively, edit the CONFIG.INI file located at /Users/[YourUsername]/Library/Application Support/Return To The Roots, setting fullscreen=1.

3. Revert Mac Resolution:
Exit the game and restore your Mac’s resolution to the default setting.

4. Restart the Game: It should now work correctly at your Mac's default resolution.

**Comment by Flamefire** [comment]
Thanks for the update. I wanted to tackle this but got side-tracked by other issues. While I don't have a Mac (which makes it hard to reproduce exactly) I found a way to reproduce this on Windows using the screen scaling option of the display settings.
I started working on a fix and it looked like a promising approach but it needs a bit more analysis and planing to make sure there are no side-effects later on.

**Comment by Runshak** [comment]
Nice to hear, that there is a fix on the way. Thanks a lot for you time and work. I still love this game after all those years

**Comment by tflinkow** [comment]
> Other Workaround. More convenient (if you are able to run the s25client.app (the App with the S2 Logo. I was not able to use this on MacOS 13.0.1:
> 
> I assume you installed it in your Applications folder. After installing, so before the first launch of the app do the following. Go to /Applications/s25client.app/Contents/MacOS and rename s25update. I used s25update_rename as new name. The important thing is, it needs a new name such that it cannot be found. Deleting should also work, but I did not test it.
> 
> start the app.

the workaround above from [here](https://github.com/Return-To-The-Roots/s25client/issues/1621#issuecomment-1791454568) works for me too, but sadly this one from [here](https://github.com/Return-To-The-Roots/s25client/issues/1621#issuecomment-2282227797) doesn't:

> Last update from me here: I got it working without having to change the macOS screen resolution each time I want to play the game:
> 
> 1. Adjust Mac Screen Resolution: Test different screen resolutions until the entire game is visible and the mouse tracks correctly within the window.
> 2. Set Fullscreen Mode in Game:
>    Start the game and navigate to Options > Graphics. Set the Mode to "Fullscreen."
>    Alternatively, edit the CONFIG.INI file located at /Users/[YourUsername]/Library/Application Support/Return To The Roots, setting fullscreen=1.
> 3. Revert Mac Resolution:
>    Exit the game and restore your Mac’s resolution to the default setting.
> 4. Restart the Game: It should now work correctly at your Mac's default resolution.

I'm on a 2020 M1 MacBook Pro. Let me know if I can do anything to help resolve the issue.

**Comment by Donderda** [comment]
I'm glad to see that I'm not the only one having this issue. For me, it doesn't occur for the latest stable build (as mentioned here). Running a 2019 MBP with an 4k monitor (if it helps).

Can I support you solving this issue?

And btw.: Thank you for bringing back my childhood and improving the game :)

**Comment by girsy01** [comment]
I also do have this issue, but neither the renaming of the update-file works nor changing the screen resolution.
I only have the game in the lower left corner and cant control the lower half of if with the mouse. Can anyone help?

**Comment by iNherjer** [comment]
I have the same issue on my 2015 MacBook Pro , none of the suggested solutions works for me 

on my MacMini M1, it runs fine without this problem

**Comment by iNherjer** [comment]
Any news on this ?

**Comment by Flamefire** [comment]
Not yet. Fix is in the works as time permits

**Comment by michi42** [comment]
Not a real fix obviously, but until it is ready, could we just disable the HiDPI feature on macOS for the time being?

```diff
diff --git a/extras/videoDrivers/SDL2/VideoSDL2.cpp b/extras/videoDrivers/SDL2/VideoSDL2.cpp
index 4fa0b49aa..8a40e9100 100644
--- a/extras/videoDrivers/SDL2/VideoSDL2.cpp
+++ b/extras/videoDrivers/SDL2/VideoSDL2.cpp
@@ -134,7 +134,7 @@ bool VideoSDL2::CreateScreen(const std::string& title, const VideoMode& size, bo
     const auto requestedSize = fullscreen ? FindClosestVideoMode(size) : size;
     unsigned commonFlags = SDL_WINDOW_OPENGL;
 
-#if SDL_VERSION_ATLEAST(2, 0, 1)
+#if SDL_VERSION_ATLEAST(2, 0, 1) && !defined(__MACOSX__)
     commonFlags |= SDL_WINDOW_ALLOW_HIGHDPI;
 #endif
```

This "fixes" the issue for me (at the cost of upscaling instead of proper HiDPI rendering evidently).

**Comment by Flamefire** [comment]
Good idea. As it is not only related to MacOS but any HighDPI system I disable that for now until I got enough time to finish the real fix: https://github.com/Return-To-The-Roots/s25client/pull/1724
