### ISSUE TITLE
s25rttr fails to compile with gcc-10.1

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1272]
It just so happened that I got a grip on gcc-10.1, and did a little test compile with the s25rttr project. There are three errors around. 

First: ‘uint8_t’ has not been declared

```
In file included from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommand.cpp:18:
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommand.h:102:46: error: ‘uint8_t’ has not been declared
  102 |     virtual void Execute(GameWorldGame& gwg, uint8_t playerId) = 0;
      |                                              ^~~~~~~


In file included from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommands.h:21,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommands.cpp:18:
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommand.h:102:46: error: ‘uint8_t’ has not been declared
  102 |     virtual void Execute(GameWorldGame& gwg, uint8_t playerId) = 0;
      |                                              ^~~~~~~
```

Second: error: ‘virtual void [...] was hidden

and third: error: ‘void [...] uint8_t)’ marked ‘override’, but does not override

here's the full build log: 
[build.log.zip](https://github.com/Return-To-The-Roots/s25client/files/4962495/build.log.zip)

please note that this is a first point release of gcc-10, it's not that stable and might contain bugs, but I wanted to provide you with an example of how the s25rttr code behaves, when compiled with the latest gcc-10 ; I hope it is helpfull :)

**Comment by stefson** [comment]
@Flamefire 

with patch from #1273 there's similar error down the road: 

```
In file included from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:18:
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:28:35: error: ‘uint8_t’ was not declared in this scope
   28 | using BoundaryStones = std::array<uint8_t, 4>;
      |                                   ^~~~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:28:45: error: template argument 1 is invalid
   28 | using BoundaryStones = std::array<uint8_t, 4>;
      |                                             ^
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:39:16: error: ‘uint8_t’ was not declared in this scope
   39 |     std::array<uint8_t, 3> roads;
      |                ^~~~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:39:26: error: template argument 1 is invalid
   39 |     std::array<uint8_t, 3> roads;
      |                          ^
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:41:5: error: ‘BoundaryStones’ does not name a type
   41 |     BoundaryStones boundary_stones;
      |     ^~~~~~~~~~~~~~
[ 71%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/gameTypes/LanGameInfo.cpp.o
```

**Comment by stefson** [comment]
and also this new error:

```
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp: In constructor ‘FoWNode::FoWNode()’:
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:24:21: error: request for member ‘begin’ in ‘((FoWNode*)this)->FoWNode::roads’, which is of non-class type ‘int’
   24 |     std::fill(roads.begin(), roads.end(), 0);
      |                     ^~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:24:36: error: request for member ‘end’ in ‘((FoWNode*)this)->FoWNode::roads’, which is of non-class type ‘int’
   24 |     std::fill(roads.begin(), roads.end(), 0);
      |                                    ^~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:25:15: error: ‘boundary_stones’ was not declared in this scope
   25 |     std::fill(boundary_stones.begin(), boundary_stones.end(), 0);
      |               ^~~~~~~~~~~~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp: In member function ‘void FoWNode::Serialize(SerializedGameData&) const’:
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:36:34: error: ‘begin’ was not declared in this scope; did you mean ‘std::begin’?
   36 |         for(unsigned char road : roads)
      |                                  ^~~~~
      |                                  std::begin
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/array:41,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:22,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:18:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/bits/range_access.h:108:37: note: ‘std::begin’ declared here
  108 |   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
      |                                     ^~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:36:34: error: ‘end’ was not declared in this scope; did you mean ‘std::end’?
   36 |         for(unsigned char road : roads)
      |                                  ^~~~~
      |                                  std::end
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/array:41,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:22,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:18:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/bits/range_access.h:110:37: note: ‘std::end’ declared here
  110 |   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
      |                                     ^~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:39:44: error: ‘boundary_stones’ was not declared in this scope; did you mean ‘boundary_stone’?
   39 |         for(unsigned char boundary_stone : boundary_stones)
      |                                            ^~~~~~~~~~~~~~~
      |                                            boundary_stone
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp: In member function ‘void FoWNode::Deserialize(SerializedGameData&)’:
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:52:35: error: ‘begin’ was not declared in this scope; did you mean ‘std::begin’?
   52 |         for(unsigned char& road : roads)
      |                                   ^~~~~
      |                                   std::begin
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/array:41,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:22,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:18:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/bits/range_access.h:108:37: note: ‘std::begin’ declared here
  108 |   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
      |                                     ^~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:52:35: error: ‘end’ was not declared in this scope; did you mean ‘std::end’?
   52 |         for(unsigned char& road : roads)
      |                                   ^~~~~
      |                                   std::end
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/array:41,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:22,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:18:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/bits/range_access.h:110:37: note: ‘std::end’ declared here
  110 |   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
      |                                     ^~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:55:45: error: ‘boundary_stones’ was not declared in this scope; did you mean ‘boundary_stone’?
   55 |         for(unsigned char& boundary_stone : boundary_stones)
      |                                             ^~~~~~~~~~~~~~~
      |                                             boundary_stone
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:61:35: error: ‘begin’ was not declared in this scope; did you mean ‘std::begin’?
   61 |         for(unsigned char& road : roads)
      |                                   ^~~~~
      |                                   std::begin
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/array:41,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:22,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:18:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/bits/range_access.h:108:37: note: ‘std::begin’ declared here
  108 |   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
      |                                     ^~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:61:35: error: ‘end’ was not declared in this scope; did you mean ‘std::end’?
   61 |         for(unsigned char& road : roads)
      |                                   ^~~~~
      |                                   std::end
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/array:41,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.h:22,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:18:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10/bits/range_access.h:110:37: note: ‘std::end’ declared here
  110 |   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
      |                                     ^~~
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/FoWNode.cpp:64:45: error: ‘boundary_stones’ was not declared in this scope; did you mean ‘boundary_stone’?
   64 |         for(unsigned char& boundary_stone : boundary_stones)
      |                                             ^~~~~~~~~~~~~~~
      |                                             boundary_stone
```

full build log: [build.log.zip](https://github.com/Return-To-The-Roots/s25client/files/4965661/build.log.zip)

**Comment by Flamefire** [comment]
Alright. Do you mind creating a PR for this? Or at least a patch which you can  attach here or in the existing PR? I don't have access to a GCC 10.1 so doing it myself isn't feasible. All you need to do is add an include `#include <cstdint>` for every file where it complains about "error: ‘uint8_t’ has not been declared" (or other (u)int<x>_t)

**Comment by stefson** [comment]
ok, so there's one more of the missing  `#include <cstdint>` , fixed by that: 

```
diff --git a/libs/s25main/gameTypes/FoWNode.h b/libs/s25main/gameTypes/FoWNode.h
index d76b1f0..67f1205 100644
--- a/libs/s25main/gameTypes/FoWNode.h
+++ b/libs/s25main/gameTypes/FoWNode.h
@@ -20,6 +20,7 @@
 
 #include "gameTypes/MapTypes.h"
 #include <array>
+#include <cstdint>
 
 class FOWObject;
 class SerializedGameData;
```

**Comment by Flamefire** [comment]
Ok, just noticed same happens for GCC 10.0 which I can get. Running now

**Comment by stefson** [comment]
I haven't seen gcc-10.0 in the wild, it was really buggy when it was released x) gcc-10.1 still has a patchset of 38 patches, which is a mouthfull for a patch release. 

In general, all new releases of gcc are prone to breaking code. But it's very rare that code fails to compile which did compile with a lower patch release. That being said, if you can get a hand on gcc-10 that should be good enough for now, so that you're able to see how to compiler behaves. 

Still, with the last missing include, there's another crash at 97% of progress. Do you want to see the log, or do you prefere to work with your own gcc-10.0 on the issue? In any case I can offer cpu time to test, just ping for a request.
