### PR TITLE
Add missing includes and update travis

### LINKED ISSUE #1272: s25rttr fails to compile with gcc-10.1
It just so happened that I got a grip on gcc-10.1, and did a little test compile with the s25rttr project. There are three errors around. 

First: ‘uint8_t’ has not been declared

```
In file included from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommand.cpp:18:
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommand.h:102:46: error: ‘uint8_t’ has not been declared
  102 |     virtual void Execute(GameWorldGame& gwg, uint8_t playerId) = 0;
      |                                              ^~~~~~~


In file included from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommands.h:21,
                 from /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommands.cpp:18:
/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameCommand.h:102:46: error: ‘uint8_t’ has not been declared
  102 |     virtual void Execute(GameWorldGame& gwg, uint8_t playerId) = 0;
      |                                              ^~~~~~~
```

Second: error: ‘virtual void [...] was hidden

and third: error: ‘void [...] uint8_t)’ marked ‘override’, but does not override

here's the full build log: 
[build.log.zip](https://github.com/Return-To-The-Roots/s25client/files/4962495/build.log.zip)

please note that this is a first point release of gcc-10, it's not that stable and might contain bugs, but I wanted to provide you with an example of how the s25rttr code behaves, when compiled with the latest gcc-10 ; I hope it is helpfull :)

### PR DESCRIPTION
**Pull request by Flamefire**
Fixes #1272

### CODE REVIEW

**Comment by Flow86** [comment]
g++10 is not available on travis?

**Comment by Flamefire** [comment]
It should have been in the PPA but seemingly is not for xenial: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=xenial

Changed that back to gcc-9

**Comment by Flamefire** [comment]
@stefson Please test this PR if it works for you now

**Comment by stefson** [comment]
looks good to me :) 

```
Return To The Roots v20200723-8bd0a2b335b73bd8a670815abaf52e4756488965
Compiled with GNU C++ version 10.1.0 for linux 64 Bit

Starting in /usr
```

also did a quick runtime test, works great

**Comment by stefson** [comment]
@chewi do you want to update your snapshot when this got merged? It allows compile with gcc-10.1.0-r2 , backport via patch seems non trivial.

**Comment by chewi** [comment]
I didn't know whether there was going to be a release soon but if not, certainly yes.

**Comment by stefson** [comment]
fun fact: gcc-10.2.0 has been released just yesterday, I installed it, compiled this branch, and it is just fine :)
