### ISSUE TITLE
s25rttr fails to compile with boost 1.81.0 with: ../libs/s25main/network/GameClient.cpp:122:9: error: 'copy_file' is deprecated

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1551]
```
/var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:122:9: error: 'copy_file' is deprecated: Use copy_options instead of copy_option [-Werror,-Wdeprecated-declarations]
        copy_file(map_path, playedMapPath, boost::filesystem::copy_option::overwrite_if_exists, ignoredEc);
        ^
/usr/include/boost/filesystem/operations.hpp:429:1: note: 'copy_file' has been explicitly marked deprecated here
BOOST_FILESYSTEM_DETAIL_DEPRECATED("Use copy_options instead of copy_option")
^
/usr/include/boost/filesystem/config.hpp:85:64: note: expanded from macro 'BOOST_FILESYSTEM_DETAIL_DEPRECATED'
#define BOOST_FILESYSTEM_DETAIL_DEPRECATED(msg) __attribute__((deprecated(msg)))
                                                               ^
1 error generated.
```

here is the full build.log: [build.log.gz](https://github.com/Return-To-The-Roots/s25client/files/10579077/build.log.gz)

the failure is the same for clang and gcc
